export { InjectS3 } from './inject-s3'
export type { S3ModuleConfig } from './s3.module'
export { S3Module } from './s3.module'
export { S3Service } from './s3.service'
export { S3_TOKEN } from './tokens'
