/**
 * Options for {@link hashPassword}.
 *
 * @example
 * const hash = await hashPassword('s3cret', { algorithm: 'argon2id', memoryCost: 19456 })
 */
export type PasswordOptions = {
  /**
   * Argon2 variant to use. Defaults to `'argon2id'`, which is the
   * recommended variant for password hashing.
   */
  algorithm?: 'argon2id' | 'argon2i' | 'argon2d'
  /**
   * Memory cost in KiB. Higher values increase resistance to GPU cracking.
   * Default 19456 (19 MiB).
   */
  memoryCost?: number
  /**
   * Time cost — number of iterations. Higher values slow down hashing.
   * Default 2.
   */
  timeCost?: number
}

/**
 * Hash a plain-text password using Argon2id via `Bun.password`.
 *
 * The resulting hash is self-contained and includes the algorithm, parameters,
 * salt, and hash value, so it can be stored directly and passed to
 * {@link verifyPassword}.
 *
 * @param plain - The plain-text password to hash.
 * @param opts - Optional hashing options. See {@link PasswordOptions}.
 * @returns A Promise that resolves to the encoded Argon2 hash string.
 *
 * @example
 * const hash = await hashPassword('s3cret')
 * const ok = await verifyPassword('s3cret', hash)
 */
export async function hashPassword(
  plain: string,
  opts?: PasswordOptions,
): Promise<string> {
  return Bun.password.hash(plain, {
    algorithm: opts?.algorithm ?? 'argon2id',
    memoryCost: opts?.memoryCost ?? 19456,
    timeCost: opts?.timeCost ?? 2,
  })
}

/**
 * Verify a plain-text password against a previously generated Argon2 hash.
 *
 * The hash format is auto-detected, so this works with hashes generated by
 * any Argon2 variant.
 *
 * @param plain - The plain-text password to verify.
 * @param hash - The encoded hash previously returned by {@link hashPassword}.
 * @returns A Promise that resolves to `true` if the password matches, `false`
 *   otherwise.
 *
 * @example
 * const ok = await verifyPassword('s3cret', hash)
 */
export async function verifyPassword(
  plain: string,
  hash: string,
): Promise<boolean> {
  return Bun.password.verify(plain, hash)
}
